package lexer

import "core:math/big"

import "../../common"

// Tokens are valid as long as the file they came from is valid
Token :: struct {
	span: common.Span,
	what: Token_Data,
}

Token_Data :: union {
	Garbage,
	Punctuation,
	Keyword,
	Identifier,
	String,
	Rune,
	Numeric,
}

Garbage :: distinct string
Identifier :: common.Identifier

String :: struct {
	raw:          string,
	value:        string, // owned
	is_raw:       bool,
	is_multiline: bool,
}

Rune :: struct {
	raw:       string,
	codepoint: rune,
}

Numeric :: struct {
	raw:    string,
	value:  big.Rat,
	format: Number_Format,
}

Number_Format :: enum {
	DecimalInteger,
	HexInteger,
	OctalInteger,
	BinaryInteger,
	Decimal,
	Float,
	HexFloat,
}

Punctuation :: enum {
	LParen = 1,
	RParen,
	LSquare,
	RSquare,
	LCurly,
	RCurly,
	Dot,
	DDot,
	Ellipsis,
	RangeExcl,
	RangeIncl,
	Comma,
	Colon,
	DColon,
	Semicolon,
	Assign,
	Move,
	EQ,
	NE,
	LT,
	GT,
	GE,
	LE,
	Arrow,
	FatArrow,
	Plus,
	Minus,
	Star,
	DStar,
	Slash,
	DSlash,
	Percent,
	Amp,
	Caret,
	At,
	Hash,
	Dollar,
	Bang,
	Question,
	Bar,
	Backslash,
	Tilde,
}

PUNCTUATION_STRINGS :: [Punctuation]string {
	.LParen    = "(",
	.RParen    = ")",
	.LSquare   = "[",
	.RSquare   = "]",
	.LCurly    = "{",
	.RCurly    = "}",
	.Dot       = ".",
	.DDot      = "..",
	.Ellipsis  = "...",
	.RangeExcl = "..<",
	.RangeIncl = "..=",
	.Comma     = ",",
	.Colon     = ":",
	.DColon    = "::",
	.Semicolon = ";",
	.Assign    = "=",
	.Move      = "<-",
	.EQ        = "==",
	.NE        = "!=",
	.LT        = "<",
	.GT        = ">",
	.GE        = ">=",
	.LE        = "<=",
	.Arrow     = "->",
	.FatArrow  = "=>",
	.Plus      = "+",
	.Minus     = "-",
	.Star      = "*",
	.DStar     = "**",
	.Slash     = "/",
	.DSlash    = "//",
	.Percent   = "%",
	.Amp       = "&",
	.Caret     = "^",
	.At        = "@",
	.Hash      = "#",
	.Dollar    = "$",
	.Bang      = "!",
	.Question  = "?",
	.Bar       = "|",
	.Backslash = "\\",
	.Tilde     = "~",
}

Keyword :: enum {
	Placeholder = 0,
	If,
	Else,
	For,
	In,
	Continue,
	Break,
	Return,
	Fail,
	Assume,
	Assert,
	Defer,
	Where,
	With,
	Using,
	Context,
	Let,
	Const,
	Type,
	Enum,
	Map,
	Struct,
	Interface,
	Impl,
	Func,
	Type_Of,
	Size_Of,
	Unit,
	Per,
	To,
	From,
	Capability,
	Requires,
	Annotation,
	Import,
	Reinterpret,
	As,
	Is,
	Is_Not,
	And,
	Or,
	Not,
	Mod,
	Auto,
	Nil,
	Zero,
	True,
	False,
	Future,
	Owned,
	Shared,
	Weak,
	Unsafe_Ptr,
	Foreign,
}

@(rodata)
KEYWORD_STRINGS := [Keyword]string {
	.Placeholder = "_",
	.If          = "if",
	.Else        = "else",
	.For         = "for",
	.In          = "in",
	.Continue    = "continue",
	.Break       = "break",
	.Return      = "return",
	.Fail        = "fail",
	.Assume      = "assume",
	.Assert      = "assert",
	.Defer       = "defer",
	.Where       = "where",
	.With        = "with",
	.Using       = "using",
	.Context     = "context",
	.Let         = "let",
	.Const       = "const",
	.Type        = "type",
	.Enum        = "enum",
	.Map         = "map",
	.Struct      = "struct",
	.Interface   = "interface",
	.Impl        = "impl",
	.Func        = "func",
	.Type_Of     = "type_of",
	.Size_Of     = "size_of",
	.Unit        = "unit",
	.Per         = "per",
	.To          = "to",
	.From        = "from",
	.Capability  = "capability",
	.Requires    = "requires",
	.Annotation  = "annotation",
	.Import      = "import",
	.Reinterpret = "reinterpret",
	.As          = "as",
	.Is          = "is",
	.Is_Not      = "is_not",
	.And         = "and",
	.Or          = "or",
	.Not         = "not",
	.Mod         = "mod",
	.Auto        = "auto",
	.Nil         = "nil",
	.Zero        = "zero",
	.True        = "true",
	.False       = "false",
	.Future      = "future",
	.Owned       = "owned",
	.Shared      = "shared",
	.Weak        = "weak",
	.Unsafe_Ptr  = "unsafe_ptr",
	.Foreign     = "foreign",
}
